name: Verify Create Dotnet Version

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  create-dotnet-versions-local:
    runs-on: ubuntu-latest
    name: Test the create-dotnet-versions locally
    steps:
      - name: Checkout
        uses: actions/checkout@v3    

      - name: Create version step
        id: dotnet-version
        uses: ./
        with:
          baseversion: 'v1.2.3-beta.4'

      - name: Echo all version outputs
        run: |
          echo "version-assembly = ${{ steps.dotnet-versions.outputs.version-assembly }}"
          echo "version-file = ${{ steps.dotnet-versions.outputs.version-file }}"
          echo "version-informational = ${{ steps.dotnet-versions.outputs.version-informational }}"
          echo "version-package = ${{ steps.dotnet-versions.outputs.version-package }}"
          echo "buildnumber = ${{ steps.dotnet-versions.outputs.buildnumber }}"