name: Verify Create Dotnet Version

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  RUNNER_DEBUG: 1

jobs:
  create-dotnet-versions-local:
    runs-on: ubuntu-latest
    name: Test the create-dotnet-versions locally
    steps:
      - name: Checkout
        uses: actions/checkout@v3    

      - name: Create version step
        id: dotnetversion
        uses: ./
        with:
          baseversion: 'v1.2.3-beta.4'

      - name: Print all output joined
        run: echo -e '${{join(steps.dotnetversion.outputs.*, '\n')}}' 

      - name: Print version-assembly
        run: echo version-assembly ${{ steps.dotnetversion.outputs.version-assembly }}                                    

      - name: Echo all version outputs
        run: |
          echo version-assembly is ${{ steps.dotnetversion.outputs.version-assembly }}
          echo "version-file = ${{ steps.dotnetversion.outputs.version-file }}"
          echo "version-informational = ${{ steps.dotnetversion.outputs.version-informational }}"
          echo "version-package = ${{ steps.dotnetversion.outputs.version-package }}"
          echo "buildnumber = ${{ steps.dotnetversion.outputs.buildnumber }}"